//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChainTicker.DataSource.Currencies.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChainTicker.DataSource.Currencies.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Code&quot;:&quot;AFN&quot;,&quot;Symbol&quot;:&quot;Af&quot;,&quot;Name&quot;:&quot;Afghan Afghani&quot;,&quot;SymbolNative&quot;:&quot;؋&quot;,&quot;DecimalPlaces&quot;:0,&quot;Image&quot;:&quot;AFN.png&quot;},{&quot;Code&quot;:&quot;ALL&quot;,&quot;Symbol&quot;:&quot;ALL&quot;,&quot;Name&quot;:&quot;Albanian Lek&quot;,&quot;SymbolNative&quot;:&quot;Lek&quot;,&quot;DecimalPlaces&quot;:0,&quot;Image&quot;:&quot;ALL.png&quot;},{&quot;Code&quot;:&quot;AUD&quot;,&quot;Symbol&quot;:&quot;AU$&quot;,&quot;Name&quot;:&quot;Australian Dollar&quot;,&quot;SymbolNative&quot;:&quot;$&quot;,&quot;DecimalPlaces&quot;:2,&quot;Image&quot;:&quot;AUD.png&quot;},{&quot;Code&quot;:&quot;AZN&quot;,&quot;Symbol&quot;:&quot;man.&quot;,&quot;Name&quot;:&quot;Azerbaijani Manat&quot;,&quot;SymbolNative&quot;:&quot;ман.&quot;,&quot;DecimalPlaces&quot;:2,&quot;Image&quot;:&quot;AZN.png&quot;},{&quot;Code&quot;:&quot;BGN&quot;,&quot;Symbol&quot;:&quot;BGN&quot;,&quot;Name&quot;:&quot;Bulgarian Lev&quot;,&quot;SymbolNative&quot....
        /// </summary>
        internal static string FiatCurrencies {
            get {
                return ResourceManager.GetString("FiatCurrencies", resourceCulture);
            }
        }
    }
}
